server:
  port: 8085

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: http://localhost:8090
          predicates:
            - Path=/products/**
        - id: costumer
          uri: http://localhost:8091
          predicates:
            - Path=/customers/**
        - id: shopping
          uri: http://localhost:8092
          predicates:
            - Path=/invoices/**

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/

